version: "3.2"
services:
  memcached:
    image: memcached:1.6-alpine
    ports:
      - "11211"
    networks:
      - memcached
    deploy:
      restart_policy:
        condition: on-failure
  plc_gen_flow_1:
    image: plc:latest
    ports:
      - target: 5502
        published: 5551
        protocol: tcp
        mode: host
    networks:
      - memcached
      - public
    depends_on:
      - memcached
    environment:
      - CONTAINER_SIMULATION="gen-flow-1"
      - CONTAINER_MEMCACHED_ADDR="memcached"
      - CONTAINER_SYSLOGDEST="SETME"
    deploy:
      restart_policy:
        condition: on-failure
  plc_gen_flow_2:
    image: plc:latest
    ports:
      - target: 5502
        published: 5552
        protocol: tcp
        mode: host
    networks:
      - memcached
      - public
    depends_on:
      - memcached
    environment:
      - CONTAINER_SIMULATION="gen-flow-2"
      - CONTAINER_MEMCACHED_ADDR="memcached"
      - CONTAINER_SYSLOGDEST="SETME"
    deploy:
      restart_policy:
        condition: on-failure
  plc_lake_level:
    image: plc:latest
    ports:
      - target: 5502
        published: 5553
        protocol: tcp
        mode: host
    networks:
      - memcached
      - public
    depends_on:
      - memcached
    environment:
      - CONTAINER_SIMULATION="lake-level"
      - CONTAINER_MEMCACHED_ADDR="memcached"
      - CONTAINER_SYSLOGDEST="SETME"
    deploy:
      restart_policy:
        condition: on-failure

networks:
  memcached:
  public:
